#!/bin/bash

export $(cat .env | grep -v ^# | xargs)
PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p 5432 -w -c "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DATABASE_NAME'" | grep -q 1 || PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USERNAME -h $POSTGRES_HOST -p 5432 -w -c "CREATE DATABASE $POSTGRES_DATABASE_NAME"